"""empty message

Revision ID: 3f52ce3f0db9
Revises: 943ee4fc9250
Create Date: 2017-06-28 09:28:27.888987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f52ce3f0db9'
down_revision = '943ee4fc9250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwrod', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passwrod')
    # ### end Alembic commands ###
