"""empty message

Revision ID: 943ee4fc9250
Revises: 87f5d1c1ec8d
Create Date: 2017-06-28 06:14:07.504689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943ee4fc9250'
down_revision = '87f5d1c1ec8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
